### ISSUE TITLE
nagios.nrpe.server state fails due to undefined cfg_dir

### ISSUE THREAD

**Issue by babilen** [saltstack-formulas/nagios-formula#20]
Ever since 5268b109a02672b9bde7df2b14ffbadf358bdc6e got merged in #16 `nagios.nrpe.server` can't be used as it causes:

```
some.minion.tld:
    Data failed to compile:
----------
    Rendering SLS 'base:nagios.nrpe.server' failed: Jinja variable 'dict object' has no attribute 'cfg_dir'
```
It would be great if this could be rectified as this breaks existing setups and alienates new users.

**Comment by babilen** [comment]
@thenewwazoo Any ideas how to deal with this?

**Comment by thenewwazoo** [comment]
Sorry I'm not in a place to submit a PR at the moment, but adding
```
...
        'conf': '/etc/nagios3/nagios.conf',
        'cfg_dir': '/etc/nagios/nrpe.d',
        'cgi_conf': '/etc/nagios3/cgi.conf',
...
```

will do the trick. Sorry I missed that.
