### ISSUE TITLE
NRPE plugin looks for plugins and fails

### ISSUE THREAD

**Issue by vishal-biyani** [saltstack-formulas/nagios-formula#28]
I don't weather to call this a bug - or lack of enough documentation for a newcomer. I will leave it to you to decide on that but here is what is happening when I tried this as a complete noob to Nagios:

NRPE plugin installation fails because it looks for plugin directory, code snippet from nagios.nrpe.plugin.sls:
```
{{ nrpe.plugin_dir }}:
  file.recurse:
    - source: salt://nagios/nrpe/files/plugins/
```

But the plugin directory does not exist in nagios/nrpe/files. I understand that ideally this is where plugins will go and is specific to how a user uses it - but leaving a empty directory or some sort of note will be helpful.

**Comment by babilen** [comment]
This is one of the many issues introduced in #16 and has not yet been addressed. This is rather unfortunate and it would be great if @thenewwazoo could provide some feedback as to how to fix this.

**Comment by thenewwazoo** [comment]
I'm not actually using salt at the moment, so I can't test this, but the fix seems pretty straightforward: add a placeholder in `nagios/nrpe/files/plugins/` in the repo. Where I did use this formula, we had a collection of plugins checked into our own repo. A placeholder directory makes sense.
